language: php

matrix:
  include:
    - php: '5.5'
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: hhvm

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh

script: 
phpunit --configuration ./tests/phpunit.xml
