language: php

dist: trusty

matrix:
  include:
    - php: '5.5'
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
  allow_failures:
    - php: hhvm

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh

script: 
  - phpunit --configuration ./tests/phpunit.xml

after_script:
  - ./tests/travis/teardown_arangodb.sh
